### Gradle properties
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

### Mod Gradle properties
net.minecraftforge.gradle.merge-source-sets=true
fabric.loom.disableObfuscation=true
multiloader.enableAdvancedVersionSearch=true
multiloader.editPublishVersions=true
multiloader.enableMixinExtrasForLegacyForge=true

### Mod properties
mod.name=Totem from Anything
mod.id=totem_from_anything
mod.version=1.0
mod.description=first line\nsecond line

### Publishing
mod.modrinth=uEiSR0ob
mod.curseforge=1252453
mod.github=stonecutter-multiloader
